// AUTO-GENERATED by fulfillment-dashboard/client-triage — do not hand-edit.
// Weeks available to the Client Triage tab, newest first. Each is lazy-loaded
// from ./triage/<week>.js only when selected, so adding history costs nothing
// on first paint.
export const WEEKS = [
 "2026-09-13",
 "2026-09-06"
];
export const LATEST = "2026-09-13";
